=== Lovor01/SKZ/SKZ-ejb/src/java/obavijestXmlSchema.xsd
<?xml version="1.0"?>
<!--
Copyright (C) 2017 kraljevic

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://meteo.hr"
           xmlns="http://meteo.hr"
           elementFormDefault="qualified">
    <xs:element name="poruka">
        <xs:complexType>
            <xs:all>
                <xs:element name="email" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="to" type="xs:normalizedString" minOccurs="1" maxOccurs="unbounded"/>
                            <xs:element name="cc" type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="bcc" type="xs:normalizedString" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="subject" type="xs:normalizedString" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="body" type="xs:string" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sms" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="number" type="xs:normalizedString" maxOccurs="1" minOccurs="1"/>
                            <xs:element name="body" type="xs:string" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Lovor01/SKZ/SKZ-ejb/test/dhz/skz/diseminacija/upozorenja/upozorenje_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2017 kraljevic

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->


<poruka
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://meteo.hr'
    xsi:schemaLocation='http://meteo.hr file:/home/kraljevic/razvoj/NetBeansProjects/SKZ/SKZ-ejb/src/java/obavijestXmlSchema.xsd'>
    <email>
        <to>pero@djetlic.org</to>
        <to>miki@maus.us</to>
        <cc>siljo@dizni.com</cc>
        <cc>vlatka@siljo.org</cc>
        <cc>jo@mo.jo</cc>
        <bcc>hura@haha.com</bcc>
        <bcc>mu@be.hr</bcc>
        <bcc>jhuhu@htv.hr</bcc>
        <subject>$vrsta: Prekoračenje $vrsta_prekoračenja koncentracija $komponenta na mjernoj postaji $postaja</subject>
        <body>
            Poštovani,
            
            na mjernoj postaji $postaja u.
        </body>
    </email>
    <sms>
        <number>+385911234567</number>
        <body>$vrsta: Na postaji $postaja u proteklih zabilježeno je prekoračenje $vrsta_prekoracenja koncentracija $komponenta.</body>
    </sms>

</poruka>
